export const messages = [
  {
    author: "ziyo",
    authorId: 1,
    msgId: 1,
    content: "Lorem ipsum",
    avatar: null,
    time: "00:00",
    msgOwner: true,
  },
  // {
  //   author: "khuja",
  //   authorId: 2,
  //   msgId: 2,
  //   content: "hello!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: false,
  // },
  // {
  //   author: "ziyo",
  //   authorId: 1,
  //   msgId: 3,
  //   content:
  //     "Lorem ipsum sit amet!!! Lorem ipsum sit amet!!!Lorem ipsum sit amet!!!Lorem ipsum sit amet!!!Lorem ipsum sit amet!!!Lorem ipsum sit amet!!! Lorem ipsum sit amet!!!Lorem ipsum sit amet!!!Lorem ipsum sit amet!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: true,
  // },
  // {
  //   author: "ziyo",
  //   authorId: 1,
  //   msgId: 4,
  //   content: "Lorem ipsum",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: true,
  // },
  // {
  //   author: "khuja",
  //   authorId: 2,
  //   msgId: 5,
  //   content: "hello!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: false,
  // },
  // {
  //   author: "ziyo",
  //   authorId: 1,
  //   msgId: 6,
  //   content: "Lorem ipsum sit amet!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: true,
  // },
  // {
  //   author: "ziyo",
  //   authorId: 1,
  //   msgId: 7,
  //   content: "Lorem ipsum",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: true,
  // },
  // {
  //   author: "khuja",
  //   authorId: 2,
  //   msgId: 8,
  //   content: "hello!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: false,
  // },
  // {
  //   author: "ziyo",
  //   authorId: 1,
  //   msgId: 9,
  //   content: "Lorem ipsum sit amet!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: true,
  // },
  // {
  //   author: "ziyo",
  //   authorId: 1,
  //   msgId: 10,
  //   content: "Lorem ipsum",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: true,
  // },
  // {
  //   author: "khuja",
  //   authorId: 2,
  //   msgId: 11,
  //   content: "hello!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: false,
  // },
  // {
  //   author: "ziyo",
  //   authorId: 1,
  //   msgId: 12,
  //   content: "Lorem ipsum sit amet!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: false,
  // },
  // {
  //   author: "ziyo",
  //   authorId: 1,
  //   msgId: 13,
  //   content: "Lorem ipsum",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: true,
  // },
  // {
  //   author: "khuja",
  //   authorId: 2,
  //   msgId: 14,
  //   content: "hello!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: false,
  // },
  // {
  //   author: "ziyo",
  //   authorId: 1,
  //   msgId: 15,
  //   content: "Lorem ipsum sit amet!!!",
  //   avatar: null,
  //   time: "00:00",
  //   msgOwner: true,
  // },
];
